### PR TITLE
Fix derive for const_generics

### LINKED ISSUE #32: canon derive macro should respect the type parameters order
If we use the canon macro on a type that has const generics, the build fails since the macro append the additional type parameters at the end, so *after* the const generic. That makes impossible to build since the order of type parameters should be always  lifetimes, then types, then consts.

### PR DESCRIPTION
**Pull request by krl**
fixes #32

### CODE REVIEW

File: canon_derive/src/lib.rs [hunk 1]
```diff
@@ -57,7 +57,9 @@ fn add_store_bound(mut generics: Generics) -> Generics {
         paren_token: None,
     });
     let mut bounds = Punctuated::new();
-    bounds.push(store_trait);
+
+    // insert at beginning, to not trip up const generics
+    bounds.insert(0, store_trait);
```
Comment (ZER0) [inline canon_derive/src/lib.rs:62]: I don't think this would work, the `store_trait` are just types, so if the structure we derive contains lifetimes we'll got the same error. Lifetimes needs to be first, then types, then consts.

**Review by ZER0 — CHANGES_REQUESTED** [review]

File: canon_derive/src/lib.rs (hunk 1 above)
Comment (krl) [reply canon_derive/src/lib.rs:62]: You cannot derive Canon for types with lifetimes anyway.

**Review by ZER0 — APPROVED** [review]
